#!/usr/bin/env sh

set -e

mkdir -p assets
stac-asset download data/sentinel-2-l2a.json assets --file-name=sentinel-2-l2a.json --s3-requester-pays
stac-asset download data/sentinel-1-grd.json assets --file-name=sentinel-1-grd.json --s3-requester-pays
